os:
  - linux
env:
  global:
    - GITHUB_REPO: "mbaguszulmi/react-travis-example"
branches:
  only:
  - master
language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - echo "[L] Installing dependencies..."
  - yarn install
script:
  - echo "[L] Start Test..."
  - yarn test
  - echo "[L] Building project..."
  - yarn build
after_success:
  - echo "[L] CD into build folder..."
  - cd build
  - echo "[L] Initializing git..."
  - git init .
  - git add .
  - git remote add origin-pages "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git"
  - git commit -m "Deploy to github pages $TRAVIS_BUILD_NUMBER"
  - git push --force origin-pages gh-pages
