os:
  - linux
env:
  global:
    - GITHUB_REPO: "mbaguszulmi/react-travis-example"
    - TARGET_BRANCH_DEPLOY: "gh-pages"
branches:
  only:
  - master
language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - echo "[L] Installing dependencies..."
  - yarn install
script:
  - echo "[L] Start Test..."
  - yarn test
  - echo "[L] Building project..."
  - yarn build
after_success:
  - echo "[L] Make deploy_git directory..."
  - mkdir deploy_git
  - cd deploy_git
  - echo "[L] Initializing git..."
  - git init .
  - git remote add origin-pages "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git"
  - git checkout -b ${TARGET_BRANCH_DEPLOY}
  - git pull origin-pages ${TARGET_BRANCH_DEPLOY}
  - rm -rf ./*
  - mv -v ../build/* ./
  - git add .
  - git commit -m "Deploy to github pages $TRAVIS_BUILD_NUMBER"
  - echo "[L] Push to ${TARGET_BRANCH_DEPLOY} branch"
  - git push --force origin-pages ${TARGET_BRANCH_DEPLOY}
